### PR TITLE
provisional fix for #2173?

### PR DESCRIPTION
**Pull request by richardsc**
This seems to easy, but I'll leave to @dankelley to check and merge.

### CODE REVIEW

**Comment by richardsc** [comment]
Hoping the fix for #2173 is this easy ...

**Review by dankelley — APPROVED** [review]
I'm going to go ahead and just merge these changes.  We have a cran deadline coming up and getting the change into oce so we can check it is the best path forward.

**Comment by dankelley** [comment]
PS to Clark -- one of the checks failed but that doesn't matter because I have that fixed in my other branch, which I plan to merge into "develop" later this morning.  We can talk about all this at Dal, if you're coming in for the morning and not just for the afternoon meeting.

**Review by dankelley — COMMENTED** [review]
I thought I just approved this.  Mixed up on GH today...

**Review by dankelley — COMMENTED** [review]
ok

**Comment by dankelley** [comment]
I think it's merged now.  I got into some kind of weird loop in doing the merging.  I'll look when I get to Dal.

**Pull request merged**
