### PR TITLE
spanish translation of po file (I)

### PR DESCRIPTION
**Pull request by pablovaldes**
first part of the file

### CODE REVIEW

**Comment by dankelley** [comment]
Thanks VERY much for this!!

**Comment by dankelley** [comment]
Pablo, please note that we are in a count-down to a release of oce on the upcoming weekend. Therefore, we will probably not take pull requests after Thursday, just to be sure that we can build the code and have it working for us for a few days before the release.  Dan.

**Comment by dankelley** [comment]
Pablo, please note that I tweaked something; in the last line below, you had forgotten the `#` character.  
```
msgid "must exceed to="
msgstr "debe de superar to="
# tricky because to can be or not part of the phrase or a variable name. 
# "debe de superar a="? "debe de exceder en="?
```

I fixed this in the `develop` branch, commit 17a3eecdcc16744d7a0744d031a6a9463986b324

Note that I found the error by running the procedure I describe at http://dankelley.github.io/r/2014/02/26/oce-translations.html which also updated some other files. I must admit that have not thought much about translations for 2 years, and so I've been forgetting to run this procedure as frequently as I should.

Thanks again. Dan.

**Comment by pablovaldes** [comment]
Thanks. I'll spend some more time in order to finish it asap.

2016-11-15 0:27 GMT+01:00 Dan Kelley <notifications@github.com>:

**Pull request merged**
