### PR TITLE
add [[ accessor description to vignette

### PR DESCRIPTION
**Pull request by richardsc**

### CODE REVIEW

**Comment by richardsc** [comment]
Note that I made another slight edit to the vignette, which was referencing `plot.ctd()` (which doesn't actually exist anymore).

I actually find that getting help on the "oce" versions of generic methods is a bit cryptic. It helps in RStudio, which will auto-complete, unless you hit the wrong key and then you lose all the auto-complete options. In the workshop I did last June, I made a point of specifically showing people the:
```r
?`plot,ctd-method`
```
way of getting to the help page, but I wonder if I'm missing a more obvious approach. I used to just do `?plot.ctd()`, but that doesn't work anymore.

**Comment by dankelley** [comment]
> On Aug 7, 2016, at 11:27 PM, Clark Richards <notifications@github.com> wrote:
> 
> 
> way of getting to the help page, but I wonder if I'm missing a more obvious approach. I used to just do ?plot.ctd(), but that doesn't work anymore.

I removed the aliases to those S3 methods for function names. Oce became S4 quite a long time ago, and I thought it was being unhelpful to suggest to users that it was S3. I don’t know whether the typical user will realize that either documentation method exists, actually. I think I’ll add something to the vignette (I’ll check first it doesn’t exist) called “getting help with oce”.  That could explain specifically things like

	?’plot,ctd-method’

and

	methods(“plot”)

I will also point out a good shortcut that I think will help users the most — get doc on *any* ctd function, and look at the seeAlso at the bottom to get links to all related functions.

**Comment by dankelley** [comment]
Thanks!

**Comment by dankelley** [comment]
I found a stray `plot.` so I fixed that and then went through the doc and used the same phrasing in each instance. I write something like

    the `A` variant of the generic `plot` function (see `help("plot,A-class")`)

throughout, so people will get used to the phrasing, and see that these are variants, and (most importantly) that "generic" is an important keyword. I also decided to say `help` instead of `?`, because I think that will be easier for people (it's what I tell new users ... they can remember that, but the `?` syntax sometimes confuses them, especially if they are C users)

**Comment by dankelley** [comment]
I made some more edits, moving the [[ section up a bit and also adding a list of why [[ is good.

**Pull request merged**
