### PR TITLE
Merge some recent rsk additions (see issue #762)

### PR DESCRIPTION
**Pull request by richardsc**
Figured I might as well just keep these merging, to prevent a big mess down the road. I've tested these changes for a day or two, and they seem good, but should still be considered preliminary.

### CODE REVIEW

**Comment by dankelley** [comment]
Thanks.  Note that we have automatic build tests now, and this was clean for that. I figure when one of us thinks code is ready to pull, and GH says it can be merged without conflict, and it passes build tests ... then we should just go for it. Thus, I accepted your modifications without really looking. I'll look sometime as the ``as.ctd()`` code, which I am guessing will be the only spot that might break users' code.

**Comment by richardsc** [comment]
Hm. One place to look for breaking is in `plotProfile()`. I think there are issues because fields like `temperature2` are not recognized as labels, and so the `resizableLabel()` tests crap out ... digging through now to see if I can figure out a good fix.

**Comment by richardsc** [comment]
Here's an example of the error I get when I do `plotProfile(ctd, xtype='temperature2')`
```
 plotProfile(ctd, xtype='temperature2')
Error in if (is.character(label) && label == "sigmaTheta") label <- resizableLabel("sigmaTheta",  (from ctd.R#3551) : 
  missing value where TRUE/FALSE needed
```

Note that it seems to work fine if *added* to an existing plot:
```
plotProfile(ctd, xtype='temperature')
plotProfile(ctd, xtype='temperature2', col=2, add=TRUE)
```

I'm not exactly sure what's going on here ...

**Comment by dankelley** [comment]
I know why this is happening, probably. It's related to this thing where ctd objects store column labels in the metadata. This goes back to very early days of oce, when ``read.ctd()`` was first written. I really don't think it makes a lot of sense because it prevents users from being able to twiddle things.  I think a users should be able to do e.g. ``x@data[["happyface"]] <- "smile"`` if they want to (ok, crazy example) but this will wreck things in ctd because it has this idea of having pretty labels.

Anyway, is there a reproducible example I can try, so I don't have to look in the code to see how the problem arose? It's easier that way for me to fix.

**Comment by dankelley** [comment]
I see now -- it's in the issue for this. I think it should work now -- does for me anyway, with newly-pushed ``develop``. Also, note that I tweaked the test code so it could run on my box, where of course I don't store ``oce`` in a directory with CR's name :smiling_imp:

**Pull request merged**
