### PR TITLE
clean up as.ctd code for argo objects

### PR DESCRIPTION
**Pull request by richardsc**
This addresses the points raised in #1176. @dankelley can you give the revised code a look and let me know what you think before merging the PR?

### CODE REVIEW

**Comment by dankelley** [comment]
Looks good. A couple of points:

1. It might be worth putting in some build checks for the profile selection, if they are not already there (I can do that if you want ... or they may already be there)

2. The doc should likely say that `profile` only works for argo at the moment

**Comment by richardsc** [comment]
Ok. I'll do number 2. Can you do number 1?

**Comment by richardsc** [comment]
Give me 5 minutes to push another commit, then you can do number 1 after merging all my changes.

**Comment by richardsc** [comment]
Done. Feel free to merge and update tests whenever you have a chance. Thanks!

**Comment by dankelley** [comment]
I added some tests in `develop` commit 3abc9b534fec3a2294227ebb75f3a322ddd73641

**Pull request merged**
