### PR TITLE
Updated help section to address issue #2136

### PR DESCRIPTION
**Pull request by avictor88**

### CODE REVIEW

**Comment by avictor88** [comment]
For sure! I'll make that edit later today - will be good to get some more practice with PRs and get a better handle on what different phrases mean in R.

**Comment by richardsc** [comment]
Damn, ran out of time, and zoom says I have to wait 9 minutes before
starting another one ...

Can you do an MS Teams meeting?

**Comment by avictor88** [comment]
Yes Teams sounds good!!

**Review by dankelley — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
