### PR TITLE
added example to mapPolygon documentation

### PR DESCRIPTION
**Pull request by j-harbin**
Hi All,

This is a simple pull request (more or less for the practice). I simply added an example to the `mapPolygon()` documentation. Note: it is the same example used for `mapImage()`. As always, only merge this change if you see fit :)

### CODE REVIEW

**Comment by dankelley** [comment]
Q: if you do
```
time Rscript 0.R
```
where `0.R` contains your example, what is the output?  I ask because on my (new and fast) machine it takes nearly 4 seconds.  I think CRAN doesn't want examples taking more than 5s each (if I recall correctly) so this might be beyond the limit.  

A solution would be to narrow the focus.  If it were 1/2 as wide and 1/2 as tall, presumably it could finish in about 1s, which would be okay.  Centring on the Arctic, though, we'd see just blue.  

I suggest you try centring somewhere else.  Since we have an example already for the Arctic, maybe do near Panama?  Or the Maritimes?  (I vote for Maritimes!). The topo is coarse, but that's just the way it is.

Actually, if we doubled the resolution of the topoWorld dataset, it would still be under 1.5Mb and it would be a lot more useful for basin-scale studies.

**Comment by j-harbin** [comment]
The time for the previous example was 5.564 on my laptop. With my most recent commit, the time was 4.610 for the subset near the Maritimes.

**Comment by dankelley** [comment]
I think it's too slow, and it should be wrapped in `\dontrun` or `\dontest` or something ... I can never remember which of them (or similar) is advised.  I think one of those 'dont' things is now *not* advised, but still permitted.  Dewey knows, I'm pretty sure.

**Comment by j-harbin** [comment]
In argoFloats we use "dontrun". Also throughout the code in `oce` "dontrun" is used. Note I also wrapped the example from `mapImage()` in don't run in my most recent commit, as that is where I got the initial example that took 5.564 seconds.

Of course, Dewey can feel free to weigh in if he thinks "donttest" is the way to go :)

**Comment by dankelley** [comment]
In oce we have both dontrun and dontest:
```
➜  R git:(develop) git grep donttest|wc
      29      29     583
➜  R git:(develop) git grep dontrun|wc
      50      52    1010
```

I did some web searching on dontrun and donttest and found from https://community.rstudio.com/t/r-cmd-check-r-4-0-0-now-runs-donttest-how-to-proceed-with-long-running-examples/64493 that R is now running `donttest` code during checks.  So maybe I'll go with that, even though we are mostly using `dontrun` in the present oce code.  Obviously, switching will be trivial if we have to.

**Pull request merged**
