### PR TITLE
tweaks to mapScalebar

### PR DESCRIPTION
**Pull request by j-harbin**
This solves issue 1751

### CODE REVIEW

**Comment by dankelley** [comment]
I'm a bit confused.  If the unit is km, do we really want 3 digits?  That's 1 metre.  I may be mixed up about what is going on ... Z if you like (but I'll be offline in 30min from now)

**Comment by dankelley** [comment]
Rejected; see https://github.com/dankelley/oce/issues/1751

Please update the docs on the legend location, and resubmit the PR.

**Review by dankelley — CHANGES_REQUESTED** [review]
You don't want to use `<<-` in line 2393.  I suggest using
```R
isProjection <- .Projection()$type != "none"
```

And, later you are also using `<<-` where it should not be a global assignment like that.

You'll need to do e.g.
```R
if (isProjection) {
    lonlat0 <- map2lonlat(x0, y0)
    lonlat1 <- map2lonlat(x1, y1)
   dkm <- geodDist(lonlat0$longitude ETC LIKE BEFORE)
} else {
    dkm <- geodDist(x0, ANALOGOUS TO OLD WAY)
} 
```
and so forth.

I'm just getting this from looking at the diff.  Maybe you can try again and I'll look again. 

The main point is that we should almost *never* use `<<-`.  That is only for very special circumstances in packages.

**Comment by j-harbin** [comment]
Hi Dan,
The push that I did initially was not a finished product, but rather a commit to not get too ahead of myself (I should have made that more clear :) )

This changes have now been completed and now allow for a scale to be created when `mapPlot()` isn't initially used. To test this try:

```R
library(oce)
data(argo)
plot(argo)
mapScalebar()
```
Screen Shot 2020-12-08 at 2 24 21 PM


For plots not created by `mapPlot()`, and

```R
library(oce)
par(mar=c(2.5, 2.5, 1, 1))
mapPlot(coastlineWorld, latitudelim=c(60, 120), longitudelim=c(-130,-50),
        col="lightgray", projection="+proj=stere +lat_0=90")
mapScalebar()
```
Screen Shot 2020-12-08 at 2 25 27 PM

Please let me know your thoughts on this, and if there is anything else you'd like to see added or removed.

**Comment by j-harbin** [comment]
``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.1.1, PROJ 6.3.1
data(argo)
plot(argo)
mapScalebar()
```



<sup>Created on 2020-12-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by j-harbin** [comment]
``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.1.1, PROJ 6.3.1
data(coastlineWorld)
## Arctic Ocean
par(mar=c(2.5, 2.5, 1, 1))
mapPlot(coastlineWorld, latitudelim=c(60, 120), longitudelim=c(-130,-50),
        col="lightgray", projection="+proj=stere +lat_0=90")
mapScalebar()
```



<sup>Created on 2020-12-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by j-harbin** [comment]
Hey Dan,

I cleaned up the code and fixed the docs (thanks for the help). It seems to all work for me. Feel free to rebuild in a half hour or so and let me know if you have any other suggestions.

**Comment by dankelley** [comment]
Looks good.  I pulled and ran a build-test sequence, and all looks fine. Thanks!

**Pull request merged**
