### PR TITLE
Fix two aquadopp bugs -- one for axis plotting and one for NA values

### PR DESCRIPTION
**Pull request by richardsc**
In doing some work on some (private) aquadopp files recently, I discovered that something seemed to be broken about the adp plot method for such instruments.

Also, I discovered that apparently sometimes an aquadopp file can have an "extra" sample, for which the time is `NA`, but other values exist, but the remaining times are all consecutive as would be expected without the NA. I don't know what causes this, and it should probably be looked into further (are we reading something wrong in the file?), but for now I added a check for such "NA times" and just remove the ensemble if any are found.

It just occurred to me that it might be a good idea to add a read-time warning that such an ensemble was found and removed.

### CODE REVIEW

**Comment by dankelley** [comment]
Can I ask what the line (in the `R/adp.nortek.R` patch)
```R
            if (!('field' %in% distance)) {
```
is doing? I thought `distance` was a numerical vector, but this line makes it look as though `distance` could also be a vector of character strings.

PS. I noticed this because the codecov entry in the previous comment (or whatever you call blocks in this webpage) is stating failure ... but I think that failure might just mean that the new code is not tested as much as the existing code; the travisCI is ok, which I care about more.

**Comment by richardsc** [comment]
Ah, good catch. That should be 

    if (!(field %in% 'distance')) {

i.e. the quotes were on the wrong things. It's just checking that it's not the `distance` field in `@data` because that's not a time series. It probably passed the test because for the aquadopps I was testing with the distance is actually just a single value (i.e. not a profile).

I'll fix that a bit later this morning. Stay tuned.

**Comment by richardsc** [comment]
Ok, let's wait for the travis check to complete, but I've fixed the above and added a warning when it finds an NA time. If you want to have a look with a data file, just let me know and I'll email it to you.

**Comment by dankelley** [comment]
Yes, please send a data file. Also, as a note: I've never seen TravisCI find a real error that Rstudio's "check" didn't find. It has some false positives, though; I'd say about 1 in 5 or 10 builds fails because it cannot download something, in setting itself up to run R, etc. (It also has to build a local gdal library, because the debian-provided one is older than the CRAN version. And that takes maybe 10 minutes to build, hence the 25min travisCI time.)

**Comment by dankelley** [comment]
I think we should just ignore the note about some tests failing, since they seem to be just codecov whining that the coverage is not high enough. Confusingly, the comment block with that info disappears once the branch has been merged.

**Pull request merged**
