### PR TITLE
Incorporating BIO's handling of ODF files within oce 

### PR DESCRIPTION
**Pull request by Xandac**
Hi Dan,

I am new to R and Git but I am making progress. Our data group here at BIO that manages the ODF format and data files is moving away from our in-house ODS (ocean data science) toolbox written in Matlab to a new toolbox in R. Since your oce package contains some of the functionality the old toolbox contained we have decided to adopt oce. This will speed things up for us since we will not have to reinvent the wheel and hopefully we can assist each other with maintenance and development. This pull request includes two functions that we created along with their documentation. I modified three of your files (NAMESPACE, AllClass.R and odf.R) to includes these functions and use them. The modification in AllClass.R was to add an odfheader class.  The modifications to odf.R were to add the full ODF header to your metadata header attribute which was NULL. We require the entire header in order to reproduce the original ODF file and we also use metadata you did not capture during our processing.  I also improved the logic in odf.R where the parameter CODE "UNKN_01" would always change to "g"; but this is only valid when "UNKN_01" refers to percent good pings for an ADCP.

If there are any issues with my pull request just let me know.

Thanks,
Jeff

### CODE REVIEW

**Comment by dankelley** [comment]
Thanks for all this. I am not going to have time to look at this until next week. I wonder if we should talk offline about design considerations, next week. The thing is that oce has a certain way of doing things, and your patch will break some of those things. For example:

1. You've made something called ``read_odf()``, which is nice because it does not clash with the existing ``read.odf()``, but it would be preferable for the two things to be combined. There is a reason for the name we have at present: the function returns an object of the ``odf`` class, so that's why there is a dot and then the name of the class.

2. You've made a new class called ``odfheader``, but the classes in oce are all designed differently, i.e. a class for a data type. We already have a class named ``odf``, so I'd prefer not to start making classes for headers.

3. It's not clear to me why one needs a class for ``odfheader``. We already have a ``metadata`` slot, and all of the information that you're suggesting should go into ``odfheader`` can (and should, I think) go into the ``metadata`` slot.

There are probably other things that will crop up, but, as noted, I won't have time this week to look in any detail. I wonder if it would be possible to arrange to meet next week to go over some items like the above. The idea would be to get your great ideas into "oce" without causing too many disruptions to the oce code and function-naming scheme. The ideal might be if you could come over to Dal some morning. I think we'd want to block out 2 hours, with a bit of time to chat at first, then maybe a bit of time to work together on strategies for blending our efforts.

PS. There are tricks that can keep your existing code working. For example, the line
```r
read_odf <- read.odf
```
creates an alias name for the existing function, which could let your existing code work with the existing name in oce (although of course, we'd be talking about updating ``read.odf``).

Your thoughts?

PS. I'm mentioning @richardsc because I don't know if the system would have emailed him with your pull request, and Clark and I make these decisions together.

**Comment by richardsc** [comment]
Hey @Xandac! If I recall correctly, we sailed together on the LabSea cruise in 2007. I was on the night shift, doing grunt work pulling oxygen samples and tossing Igor's XBT's off the back of the ship. 

This is a huge amount of work, and it think it will make a great addition to oce. As Dan mentioned, there are definitely a few things to work, and I agree with him that it would be good for you two to meet in person to hash out some of the details (I'm bummed I can't be there -- currently in NB on vacation, but I'm living in Ottawa now).

1. Regarding the `odfheader` I can see an argument why you would want it to have it's own structure within the metadata slot, though it would definitely "fit" better with the oce way of doing things if the "header" fields are simply used as fields in the `@metadata` slot. That probably would be something you two could hash out pretty quickly face-to-face.

2. There will be some issues with copyrights and authorship that we will need to sort out. I noticed that the details section of the new `read_odf()` function has quite a bit of "source", "author", "copyright", and "modification" information. Because of the nature of CRAN and the R package distribution, this all has to be clearly indicated in the `DESCRIPTION` file.

3. Relatedly, we may also need to think about the license, if DFO is involved. Currently oce is licensed as a combination of GPL-2 and GPL-3. See [https://cran.r-project.org/web/packages/oce/index.html](https://cran.r-project.org/web/packages/oce/index.html) for details. This is actually a big deal, because it can determine whether CRAN will actually accept it as a package and distribute it.

In the future, I encourage you to use the "Issues" page to open discussion before making large pull requests. Typically, we try and make changes a small amount at a time, to facilitate integration and avoid duplication of effort. 

I'm excited that we'll be able to get more functionality to the `odf` capabilities! :)

**Comment by Xandac** [comment]
Hi Dan and Richard,

Your comments, suggestions and logic all make great sense. I am totally new to Git so understanding the best way of doing things will take some time for me to grasp; plus I do not want to throw a wrench into your finely tuned machine. It would be great to meet some time in the near future but it will not happen for at least a couple of weeks. I would prefer to have Gordana join me when we meet and she is away until the end of August or early September so that might be possible depending on your schedule as school approaches.

I too am looking forward to working together and making oce stronger.

Cheers,
Jeff

**Comment by dankelley** [comment]
School is actually a good time for me for finding an hour here and an hour there, so this will work out well. In the meantime, I wonder if I could get your opinion on the idea of having the ODV information be in a a list (or items in a list) instead of in a S4 class. If you think it would be ok to drop the S4 class, please let me know, because then my inclination would be to start transferring some of the elements into oce, testing against some ODV data that I'm using now to be sure not to break things.  It would also help enormously if you could send me a dropbox link or something, with a suite of ODV files (use private email to me, to keep your data private).  The one thing I've learned with oce is that code written for one datafile tends to break on the next one, and I love to have a suite of data so that I can run through the development code and check for veracity.

But, if you want to just leave it all until January, that's fine also.  I've a lot on my plate, anyway!

Dan.

**Comment by richardsc** [comment]
Just to be clear: you mean ODF data, right @dankelley? Not ODV (i.e. OceanDataView).

**Comment by dankelley** [comment]
@richardsc Hilarious -- yup, I meant ODF. Either I typed it wrong or it autocorrected. I hate ODV ...

**Comment by Xandac** [comment]
Our read_odf.R function uses a list instead of a class so that is not an issue. Your library uses lots of classes and I am new to classes so I thought I would create the odfHeader class (mostly learning experience) but that can easily be dropped.  We need everything from the ODF header saved according to each header type (ODF_HEADER, CRUISE_HEADER, EVENT_HEADER, etc.); how that is stored internally is not as important as keeping the header lists together.  I can definitely send you a bunch of ODF files to test but first I will send you the testthat files that a colleague created to test read_odf.R; hopefully they are a good place to start before I send you data files.

Jeff

**Comment by dankelley** [comment]
I'm closing this because discussion here and elsewhere has led to the conclusion that pulling this branch will not accomplish the underlying goals. As of now, we have ``oce::ODF2oce()`` to provide a provisional conversion from items returned by ``ODF::read_odf()`` to oce objects. Note that this ODF function, and indeed the whole ODF package, is not yet publicly available, and that therefore ``oce::ODF2oce()`` may need to be changed when ODF is released.  (Well, I am assuming it will be released ... if not, I still will try to keep ``oce:ODF2oce()`` abrest of changes in ``ODF::read_odf()``.)

**Pull request closed without merging**
