### PR TITLE
Various man page fixes, including formatting and the S35T15 conductiv…

### PR DESCRIPTION
**Pull request by richardsc**
…ity ratio value for swCSTp

### CODE REVIEW

**Comment by dankelley** [comment]
I'm mixed up. From the GH (or email, not sure) it seems that you went back on the changes? Should I still merge?

**Comment by richardsc** [comment]
Yes, this can be merged. Just a few small man page fixes, the most important of which is the erroneous value for C(S=35, T=15, p=0) in the man page for `swCSTp()`.

**Comment by dankelley** [comment]
Why did you insert spaces after some opening braces?

**Comment by dankelley** [comment]
I merged and cleaned up some ``{ `` inconsistencies (in several files) and pushed back.

**Comment by richardsc** [comment]
I put the spaces in because I noticed in the associated help files (both plain texinfo, i.e. terminal, and html) that the `\item{}` and the description were being run together. See the screenshots (from the just-pulled version):
screen shot 2015-07-12 at 8 49 53 am
screen shot 2015-07-12 at 8 50 25 am
screen shot 2015-07-12 at 8 51 08 am

**Comment by richardsc** [comment]
You could say that this was a case of RTFM (read the formatted manual) ...

**Pull request merged**
