### PR TITLE
spanish translation of R-es.po

### PR DESCRIPTION
**Pull request by pablovaldes**
All messages in the file translated and reviewed, except those tagged as fuzzy with diferent meanings for msgid and msgstr

All messages previously translated by me were also redone and greatly improved

As longitud is the same spanish word for 'longitude' and 'length' a lot of messages where ambiguous. The lacking context was provided adding 'vector length' or 'column length' when needed to understand the message. Longitude instead was changed to 'coord. longitude' also to avoid ambiguity.

Traslating beam as 'haz' or 'haz de barrido'. A beam can be made of light but also of ultrasounds so laser or ray was not entirely correct for all situations.

### CODE REVIEW

**Comment by dankelley** [comment]
Thanks VERY much for all this work!!

**Comment by pablovaldes** [comment]
Thank you, oce is a great package :-)

**Comment by dankelley** [comment]
Pablo, can you send me a private email to kelley.dan@gmail.com so I can ask a question about your contribution? Thanks.

**Comment by dankelley** [comment]
I fixed up a few syntax errors and pushed to `develop`.

**Pull request merged**
